name: Terraform and Packer AWS Automation Destroy

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Resources to be destroyed'
        required: false
        

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARGS: "-av"

jobs:
   packer_terraform_destroy:
    name: 'packer_terraform_destroy'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: './scripts'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies python
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Install Jq
        id: jq_install
        run: |
            mkdir -p ${HOME}/.local/bin
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O ${HOME}/.local/bin/jq
            chmod +x ${HOME}/.local/bin/jq
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        shell: bash    

      - name: Init script terraform-packer-aws.sh
        id: init_script
        run: |
            chmod +x terraform-packer-aws.sh 
            ./terraform-packer-aws.sh destroy
        shell: bash
